import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from '../components/Navbar';
import Footer from '../components/footer';

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100" , "200" , "300" , "400" , "500" , "600" , "700" , "800" , "900"]
});

export const metadata: Metadata = {
  title: "Student Performance Evaluator",
  description: "Generated by NextJS and FastAPI",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} relative bg-neutral-100`}>
        <div className="absolute inset-0 -z-10 h-full w-full bg-neutral-50 bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]"></div>
        <Navbar />
        <main className="max-w-7xl px-4 mx-auto">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
